// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryManagementApp.Data;

#nullable disable

namespace SalaryManagementApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221213135343_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("SalaryManagementApp.Models.Account", b =>
                {
                    b.Property<int>("AccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SalaryManagementApp.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("BonusAddedNetSalary")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("NetSalary")
                        .HasColumnType("REAL");

                    b.Property<float>("Salary")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalSalary")
                        .HasColumnType("REAL");

                    b.HasKey("EId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SalaryManagementApp.Models.Salary", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("SalaryFrom")
                        .HasColumnType("REAL");

                    b.Property<float>("SalaryTo")
                        .HasColumnType("REAL");

                    b.Property<float>("Tax")
                        .HasColumnType("REAL");

                    b.Property<float>("YearlyBonusPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("SId");

                    b.ToTable("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
